---
kind: pipeline
type: docker
name: commit_lint

steps:

- name: commit lint
  image: extenda/commitlint
  commands:
  - commitlint --from=HEAD~1


---
kind: pipeline
type: docker
name: test_build_publish_pipeline

platform:
  arch: amd64

steps:

- name: test
  image: python:3.6.9-slim-buster
  commands:
  - pip install -r requirements.txt
  - pip install pytest
  - pytest -rA tests/

- name: build
  image: plugins/docker
  settings:
    insecure: true
    registry: 101.0.0.1:5002
    repo: 101.0.0.1:5002/test/godaddy_ddns
    tags: latest

depends_on:
- commit_lint


---
kind: pipeline
name: deploy_pipeline

workspace:
  path: /home/user/projects/godaddy_ddns

steps:
- name: run_local
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker pull 101.0.0.1:5002/test/godaddy_ddns
  - if (docker ps -a | grep godaddy_ddns); then docker stop godaddy_ddns; fi
  - docker run -d --rm -v `pwd`/envs:/usr/src/app/envs/:ro -v `pwd`/logs:/usr/src/app/logs/:rw --user $(id -u ${USER}):$(id -g ${USER}) --name godaddy_ddns 101.0.0.1:5002/test/godaddy_ddns

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock

depends_on:
- test_build_publish_pipeline
